COUNTRIES = (
    (u'AF', u'Afghanistan', u'+93'),
    (u'AX', u'\xc5land Islands', u'+358'),
    (u'AL', u'Albania', u'+355'),
    (u'DZ', u'Algeria', u'+213'),
    (u'AS', u'American Samoa', u'+1684'),
    (u'AD', u'Andorra', u'+376'),
    (u'AO', u'Angola', u'+244'),
    (u'AI', u'Anguilla', u'+1264'),
    (u'AQ', u'Antarctica', u'+672'),
    (u'AG', u'Antigua and Barbuda', u'+1268'),
    (u'AR', u'Argentina', u'+54'),
    (u'AM', u'Armenia', u'+374'),
    (u'AW', u'Aruba', u'+297'),
    (u'AU', u'Australia', u'+61'),
    (u'AT', u'Austria', u'+43'),
    (u'AZ', u'Azerbaijan', u'+994'),
    (u'BS', u'Bahamas', u'+1242'),
    (u'BH', u'Bahrain', u'+973'),
    (u'BD', u'Bangladesh', u'+880'),
    (u'BB', u'Barbados', u'+1246'),
    (u'BY', u'Belarus', u'+375'),
    (u'BE', u'Belgium', u'+32'),
    (u'BZ', u'Belize', u'+501'),
    (u'BJ', u'Benin', u'+229'),
    (u'BM', u'Bermuda', u'+1441'),
    (u'BT', u'Bhutan', u'+975'),
    (u'BO', u'Bolivia', u'+591'),
    (u'BA', u'Bosnia and Herzegovina', u'+387'),
    (u'BW', u'Botswana', u'+267'),
    (u'BV', u'Bouvet Island', u'+47'),
    (u'BR', u'Brazil', u'+55'),
    (u'IO', u'British Indian Ocean Territory', u'+246'),
    (u'BN', u'Brunei Darussalam', u'+673'),
    (u'BG', u'Bulgaria', u'+359'),
    (u'BF', u'Burkina Faso', u'+226'),
    (u'BI', u'Burundi', u'+257'),
    (u'KH', u'Cambodia', u'+855'),
    (u'CM', u'Cameroon', u'+237'),
    (u'CA', u'Canada', u'+1'),
    (u'CV', u'Cape Verde', u'+238'),
    (u'KY', u'Cayman Islands', u'+ 345'),
    (u'CF', u'Central African Republic', u'+236'),
    (u'TD', u'Chad', u'+235'),
    (u'CL', u'Chile', u'+56'),
    (u'CN', u'China', u'+86'),
    (u'CX', u'Christmas Island', u'+61'),
    (u'CC', u'Cocos (Keeling) Islands', u'+61'),
    (u'CO', u'Colombia', u'+57'),
    (u'KM', u'Comoros', u'+269'),
    (u'CG', u'Congo', u'+242'),
    (u'CD', u'Congo, The Democratic Republic of The', u'+243'),
    (u'CK', u'Cook Islands', u'+682'),
    (u'CR', u'Costa Rica', u'+506'),
    (u'CI', u"Cote D'ivoire", u'+225'),
    (u'HR', u'Croatia', u'+385'),
    (u'CU', u'Cuba', u'+53'),
    (u'CY', u'Cyprus', u'+357'),
    (u'CZ', u'Czech Republic', u'+420'),
    (u'DK', u'Denmark', u'+45'),
    (u'DJ', u'Djibouti', u'+253'),
    (u'DM', u'Dominica', u'+1767'),
    (u'DO', u'Dominican Republic', u'+1849'),
    (u'EC', u'Ecuador', u'+593'),
    (u'EG', u'Egypt', u'+20'),
    (u'SV', u'El Salvador', u'+503'),
    (u'GQ', u'Equatorial Guinea', u'+240'),
    (u'ER', u'Eritrea', u'+291'),
    (u'EE', u'Estonia', u'+372'),
    (u'ET', u'Ethiopia', u'+251'),
    (u'FK', u'Falkland Islands (Malvinas)', u'+500'),
    (u'FO', u'Faroe Islands', u'+298'),
    (u'FJ', u'Fiji', u'+679'),
    (u'FI', u'Finland', u'+358'),
    (u'FR', u'France', u'+33'),
    (u'GF', u'French Guiana', u'+594'),
    (u'PF', u'French Polynesia', u'+689'),
    (u'TF', u'French Southern Territories', u'+262'),
    (u'GA', u'Gabon', u'+241'),
    (u'GM', u'Gambia', u'+220'),
    (u'GE', u'Georgia', u'+995'),
    (u'DE', u'Germany', u'+49'),
    (u'GH', u'Ghana', u'+233'),
    (u'GI', u'Gibraltar', u'+350'),
    (u'GR', u'Greece', u'+30'),
    (u'GL', u'Greenland', u'+299'),
    (u'GD', u'Grenada', u'+1473'),
    (u'GP', u'Guadeloupe', u'+590'),
    (u'GU', u'Guam', u'+1671'),
    (u'GT', u'Guatemala', u'+502'),
    (u'GG', u'Guernsey', u'+44'),
    (u'GN', u'Guinea', u'+224'),
    (u'GW', u'Guinea-bissau', u'+245'),
    (u'GY', u'Guyana', u'+592'),
    (u'HT', u'Haiti', u'+509'),
    (u'VA', u'Holy See (Vatican City State)', u'+379'),
    (u'HN', u'Honduras', u'+504'),
    (u'HK', u'Hong Kong', u'+852'),
    (u'HU', u'Hungary', u'+36'),
    (u'IS', u'Iceland', u'+354'),
    (u'IN', u'India', u'+91'),
    (u'ID', u'Indonesia', u'+62'),
    (u'IR', u'Iran, Islamic Republic of', u'+98'),
    (u'IQ', u'Iraq', u'+964'),
    (u'IE', u'Ireland', u'+353'),
    (u'IM', u'Isle of Man', u'+44'),
    (u'IL', u'Israel', u'+972'),
    (u'IT', u'Italy', u'+39'),
    (u'JM', u'Jamaica', u'+1876'),
    (u'JP', u'Japan', u'+81'),
    (u'JE', u'Jersey', u'+44'),
    (u'JO', u'Jordan', u'+962'),
    (u'KZ', u'Kazakhstan', u'+7'),
    (u'KE', u'Kenya', u'+254'),
    (u'KI', u'Kiribati', u'+686'),
    (u'KP', u"Korea, Democratic People's Republic of", u'+850'),
    (u'KR', u'Korea, Republic of', u'+82'),
    (u'KW', u'Kuwait', u'+965'),
    (u'KG', u'Kyrgyzstan', u'+996'),
    (u'LA', u"Lao People's Democratic Republic", u'+856'),
    (u'LV', u'Latvia', u'+371'),
    (u'LB', u'Lebanon', u'+961'),
    (u'LS', u'Lesotho', u'+266'),
    (u'LR', u'Liberia', u'+231'),
    (u'LY', u'Libyan Arab Jamahiriya', u'+218'),
    (u'LI', u'Liechtenstein', u'+423'),
    (u'LT', u'Lithuania', u'+370'),
    (u'LU', u'Luxembourg', u'+352'),
    (u'MO', u'Macao', u'+853'),
    (u'MK', u'Macedonia, The Former Yugoslav Republic of', u'+389'),
    (u'MG', u'Madagascar', u'+261'),
    (u'MW', u'Malawi', u'+265'),
    (u'MY', u'Malaysia', u'+60'),
    (u'MV', u'Maldives', u'+960'),
    (u'ML', u'Mali', u'+223'),
    (u'MT', u'Malta', u'+356'),
    (u'MH', u'Marshall Islands', u'+692'),
    (u'MQ', u'Martinique', u'+596'),
    (u'MR', u'Mauritania', u'+222'),
    (u'MU', u'Mauritius', u'+230'),
    (u'YT', u'Mayotte', u'+262'),
    (u'MX', u'Mexico', u'+52'),
    (u'FM', u'Micronesia, Federated States of', u'+691'),
    (u'MD', u'Moldova, Republic of', u'+373'),
    (u'MC', u'Monaco', u'+377'),
    (u'MN', u'Mongolia', u'+976'),
    (u'ME', u'Montenegro', u'+382'),
    (u'MS', u'Montserrat', u'+1664'),
    (u'MA', u'Morocco', u'+212'),
    (u'MZ', u'Mozambique', u'+258'),
    (u'MM', u'Myanmar', u'+95'),
    (u'NA', u'Namibia', u'+264'),
    (u'NR', u'Nauru', u'+674'),
    (u'NP', u'Nepal', u'+977'),
    (u'NL', u'Netherlands', u'+31'),
    (u'AN', u'Netherlands Antilles', u'+599'),
    (u'NC', u'New Caledonia', u'+687'),
    (u'NZ', u'New Zealand', u'+64'),
    (u'NI', u'Nicaragua', u'+505'),
    (u'NE', u'Niger', u'+227'),
    (u'NG', u'Nigeria', u'+234'),
    (u'NU', u'Niue', u'+683'),
    (u'NF', u'Norfolk Island', u'+672'),
    (u'MP', u'Northern Mariana Islands', u'+1670'),
    (u'NO', u'Norway', u'+47'),
    (u'OM', u'Oman', u'+968'),
    (u'PK', u'Pakistan', u'+92'),
    (u'PW', u'Palau', u'+680'),
    (u'PS', u'Palestinian Territory, Occupied', u'+970'),
    (u'PA', u'Panama', u'+507'),
    (u'PG', u'Papua New Guinea', u'+675'),
    (u'PY', u'Paraguay', u'+595'),
    (u'PE', u'Peru', u'+51'),
    (u'PH', u'Philippines', u'+63'),
    (u'PN', u'Pitcairn', u'+64'),
    (u'PL', u'Poland', u'+48'),
    (u'PT', u'Portugal', u'+351'),
    (u'PR', u'Puerto Rico', u'+1939'),
    (u'QA', u'Qatar', u'+974'),
    (u'RE', u'Reunion', u'+262'),
    (u'RO', u'Romania', u'+40'),
    (u'RU', u'Russian Federation', u'+7'),
    (u'RW', u'Rwanda', u'+250'),
    (u'SH', u'Saint Helena', u'+290'),
    (u'KN', u'Saint Kitts and Nevis', u'+1869'),
    (u'LC', u'Saint Lucia', u'+1758'),
    (u'PM', u'Saint Pierre and Miquelon', u'+508'),
    (u'VC', u'Saint Vincent and The Grenadines', u'+1784'),
    (u'WS', u'Samoa', u'+685'),
    (u'SM', u'San Marino', u'+378'),
    (u'ST', u'Sao Tome and Principe', u'+239'),
    (u'SA', u'Saudi Arabia', u'+966'),
    (u'SN', u'Senegal', u'+221'),
    (u'RS', u'Serbia', u'+381'),
    (u'SC', u'Seychelles', u'+248'),
    (u'SL', u'Sierra Leone', u'+232'),
    (u'SG', u'Singapore', u'+65'),
    (u'SK', u'Slovakia', u'+421'),
    (u'SI', u'Slovenia', u'+386'),
    (u'SB', u'Solomon Islands', u'+677'),
    (u'SO', u'Somalia', u'+252'),
    (u'ZA', u'South Africa', u'+27'),
    (u'GS', u'South Georgia and The South Sandwich Islands', u'+500'),
    (u'ES', u'Spain', u'+34'),
    (u'LK', u'Sri Lanka', u'+94'),
    (u'SD', u'Sudan', u'+249'),
    (u'SR', u'Suriname', u'+597'),
    (u'SJ', u'Svalbard and Jan Mayen', u'+47'),
    (u'SZ', u'Swaziland', u'+268'),
    (u'SE', u'Sweden', u'+46'),
    (u'CH', u'Switzerland', u'+41'),
    (u'SY', u'Syrian Arab Republic', u'+963'),
    (u'TW', u'Taiwan, Province of China', u'+886'),
    (u'TJ', u'Tajikistan', u'+992'),
    (u'TZ', u'Tanzania, United Republic of', u'+255'),
    (u'TH', u'Thailand', u'+66'),
    (u'TL', u'Timor-leste', u'+670'),
    (u'TG', u'Togo', u'+228'),
    (u'TK', u'Tokelau', u'+690'),
    (u'TO', u'Tonga', u'+676'),
    (u'TT', u'Trinidad and Tobago', u'+1868'),
    (u'TN', u'Tunisia', u'+216'),
    (u'TR', u'Turkey', u'+90'),
    (u'TM', u'Turkmenistan', u'+993'),
    (u'TC', u'Turks and Caicos Islands', u'+1649'),
    (u'TV', u'Tuvalu', u'+688'),
    (u'UG', u'Uganda', u'+256'),
    (u'UA', u'Ukraine', u'+380'),
    (u'AE', u'United Arab Emirates', u'+971'),
    (u'GB', u'United Kingdom', u'+44'),
    (u'US', u'United States', u'+1'),
    (u'UM', u'United States Minor Outlying Islands', u'+1'),
    (u'UY', u'Uruguay', u'+598'),
    (u'UZ', u'Uzbekistan', u'+998'),
    (u'VU', u'Vanuatu', u'+678'),
    (u'VE', u'Venezuela', u'+58'),
    (u'VN', u'Viet Nam', u'+84'),
    (u'VG', u'Virgin Islands, British', u'+1284'),
    (u'VI', u'Virgin Islands, U.S.', u'+1340'),
    (u'WF', u'Wallis and Futuna', u'+681'),
    (u'EH', u'Western Sahara', u'+212'),
    (u'YE', u'Yemen', u'+967'),
    (u'ZM', u'Zambia', u'+260'),
    (u'ZW', u'Zimbabwe', u'+263'),
)


def resolve(country_code):
    country_code = country_code.upper()
    for country in COUNTRIES:
        if country_code == country[0]:
            return country

    return None


def detect(ip):
    from geoip import geolite2
    match = geolite2.lookup(ip)
    return match.country if match else None

COUNTRY_CHOICES = tuple((c[0], c[1]) for c in COUNTRIES)
