"""empty message

Revision ID: 000f5bf3cec1
Revises: 3d7298ce2498
Create Date: 2017-12-19 11:40:02.811676

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql


# revision identifiers, used by Alembic.
revision = '000f5bf3cec1'
down_revision = '3d7298ce2498'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'products', sa.Column('approved_count', sa.Integer(), nullable=True))
    op.execute('UPDATE products SET approved_count=0')
    op.alter_column(u'products', 'approved_count', existing_type=mysql.INTEGER(display_width=11), nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'approved_count')
    # ### end Alembic commands ###
