"""empty message

Revision ID: 002e4fc2ca32
Revises: a049c0e31187
Create Date: 2018-01-27 16:23:23.969894

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '002e4fc2ca32'
down_revision = 'a049c0e31187'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_skills',
    sa.Column('content_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('skill_name', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], onupdate='cascade', ondelete='cascade'),
    sa.PrimaryKeyConstraint('content_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_skills')
    # ### end Alembic commands ###
