"""empty message

Revision ID: 010943f52ad0
Revises: 4d67439e581f
Create Date: 2018-01-29 11:30:38.343709

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '010943f52ad0'
down_revision = '4d67439e581f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('is_recommended', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'is_recommended')
    # ### end Alembic commands ###
