"""empty message

Revision ID: 0ab50daec735
Revises: 15f4166c21e2
Create Date: 2018-01-30 10:27:51.069037

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils

LEVELS = [
	('new_seller', 'New Seller'),
	('level_1', 'Level 1 Seller'),
	('level_2', 'Level 2 Seller'),
	('top_rated', 'Top Rated Seller')
]



# revision identifiers, used by Alembic.
revision = '0ab50daec735'
down_revision = '15f4166c21e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('complete_orders', sa.Integer(), server_default='0'))
    op.add_column('users', sa.Column('half_five_achieve_on', sa.Date(), nullable=True))
    op.add_column('users', sa.Column('level', sqlalchemy_utils.types.choice.ChoiceType(LEVELS), server_default='new_seller', default=u'new_seller'))
    op.add_column('users', sa.Column('rating', sa.Float(precision=1, asdecimal=True), server_default='0'))
    op.add_column('users', sa.Column('total_earns', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'total_earns')
    op.drop_column('users', 'rating')
    op.drop_column('users', 'level')
    op.drop_column('users', 'half_five_achieve_on')
    op.drop_column('users', 'complete_orders')
    # ### end Alembic commands ###
