"""empty message

Revision ID: 15aa4eba5862
Revises: baba93b16da5
Create Date: 2017-10-27 15:38:59.162755

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15aa4eba5862'
down_revision = 'baba93b16da5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('profile_headline', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'profile_headline')
    # ### end Alembic commands ###
