"""empty message

Revision ID: 15f4166c21e2
Revises: 43e2bffad962
Create Date: 2018-01-29 16:37:07.903053

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15f4166c21e2'
down_revision = '43e2bffad962'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('votes', sa.Integer(), nullable=True, server_default='0'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'votes')
    # ### end Alembic commands ###
