"""empty message

Revision ID: 1a876895af2c
Revises: ca99be2cb6e2
Create Date: 2018-01-31 13:52:41.156145

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a876895af2c'
down_revision = 'ca99be2cb6e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('registered_ip', sa.String(length=46), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'registered_ip')
    # ### end Alembic commands ###
