"""empty message

Revision ID: 20511d8d8e5b
Revises: 9c2582c04f6b
Create Date: 2017-11-30 17:09:43.057076

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20511d8d8e5b'
down_revision = '9c2582c04f6b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('subtype', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'subtype')
    # ### end Alembic commands ###
