"""empty message

Revision ID: 25d44ae321ee
Revises: 452b84408179
Create Date: 2017-12-17 20:22:27.279909

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '25d44ae321ee'
down_revision = '452b84408179'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_invitations', sa.Column('uuid', sa.String(length=36), nullable=True))
    op.create_index(op.f('ix_user_invitations_uuid'), 'user_invitations', ['uuid'], unique=False)
    op.drop_index('unique_id', table_name='user_invitations')
    op.drop_column('user_invitations', 'unique_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_invitations', sa.Column('unique_id', mysql.VARCHAR(length=100), nullable=True))
    op.create_index('unique_id', 'user_invitations', ['unique_id'], unique=True)
    op.drop_index(op.f('ix_user_invitations_uuid'), table_name='user_invitations')
    op.drop_column('user_invitations', 'uuid')
    # ### end Alembic commands ###
