"""empty message

Revision ID: 27be1edf6226
Revises: 7884e1103bf9
Create Date: 2017-08-17 13:06:37.668247

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27be1edf6226'
down_revision = '7884e1103bf9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('tz', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'tz')
    # ### end Alembic commands ###
