"""verification_random_code

Revision ID: 29afcbb970e5
Revises: 619d8b1c16a9
Create Date: 2018-01-30 11:58:16.904465

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '29afcbb970e5'
down_revision = '619d8b1c16a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_verifications', sa.Column('random_code', sa.String(length=128), nullable=True))
    op.alter_column('user_verifications', 'created_on',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('user_verifications', 'state',
               existing_type=mysql.VARCHAR(length=20),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_verifications', 'state',
               existing_type=mysql.VARCHAR(length=20),
               nullable=True)
    op.alter_column('user_verifications', 'created_on',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.drop_column('user_verifications', 'random_code')
    # ### end Alembic commands ###
