"""empty message

Revision ID: 2a6a2d3bcda6
Revises: 7def23d4b595
Create Date: 2017-06-20 15:06:02.931213

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a6a2d3bcda6'
down_revision = '7def23d4b595'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('disputes', sa.Column('kind', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('disputes', 'kind')
    # ### end Alembic commands ###
