"""empty message

Revision ID: 3d7298ce2498
Revises: fe3f6db1e170
Create Date: 2017-12-18 13:17:08.724878

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d7298ce2498'
down_revision = 'fe3f6db1e170'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_invitations', sa.Column('invited_user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user_invitations', 'users', ['invited_user_id'], ['user_id'], onupdate='set null', ondelete='set null')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_invitations', type_='foreignkey')
    op.drop_column('user_invitations', 'invited_user_id')
    # ### end Alembic commands ###
