"""empty message

Revision ID: 3ff0396e0c85
Revises: d11eb19bd206
Create Date: 2017-11-10 11:57:46.820828

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3ff0396e0c85'
down_revision = 'd11eb19bd206'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('enquiries', sa.Column('seller_id', sa.Integer(), nullable=True))
    op.alter_column('enquiries', 'product_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.create_foreign_key(None, 'enquiries', 'users', ['seller_id'], ['user_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'enquiries', type_='foreignkey')
    op.alter_column('enquiries', 'product_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.drop_column('enquiries', 'seller_id')
    # ### end Alembic commands ###
