"""empty message

Revision ID: 42a046e621b1
Revises: df6d7cd53bbc
Create Date: 2017-12-11 15:17:37.467418

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42a046e621b1'
down_revision = 'df6d7cd53bbc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('enquiry_offers', sa.Column('revision_count', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('enquiry_offers', 'revision_count')
    # ### end Alembic commands ###
