"""empty message

Revision ID: 452b84408179
Revises: f14255148eda
Create Date: 2017-12-17 20:16:58.269962

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '452b84408179'
down_revision = 'f14255148eda'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_invitations', sa.Column('unique_id', sa.String(length=100), nullable=True))
    # op.drop_index('ix_user_contacts_email', table_name='user_invitations')
    op.create_unique_constraint(None, 'user_invitations', ['unique_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_invitations', type_='unique')
    # op.create_index('ix_user_contacts_email', 'user_invitations', ['email'], unique=False)
    op.drop_column('user_invitations', 'unique_id')
    # ### end Alembic commands ###
