"""empty message

Revision ID: 4d67439e581f
Revises: 002e4fc2ca32
Create Date: 2018-01-27 16:49:21.507461

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d67439e581f'
down_revision = '002e4fc2ca32'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_languages',
    sa.Column('content_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('language_name', sa.String(length=20), nullable=True),
    sa.Column('language_level', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], onupdate='cascade', ondelete='cascade'),
    sa.PrimaryKeyConstraint('content_id')
    )
    op.create_index(op.f('ix_user_languages_language_level'), 'user_languages', ['language_level'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_languages_language_level'), table_name='user_languages')
    op.drop_table('user_languages')
    # ### end Alembic commands ###
