"""empty message

Revision ID: 512210274e52
Revises: 6477efbb4edf
Create Date: 2017-06-06 14:51:39.746519

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '512210274e52'
down_revision = '6477efbb4edf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('requirements_provided_on', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'requirements_provided_on')
    # ### end Alembic commands ###
