"""verification_photo

Revision ID: 619d8b1c16a9
Revises: 4d67439e581f
Create Date: 2018-01-29 11:39:50.069464

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '619d8b1c16a9'
down_revision = '4d67439e581f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_verification_photos',
    sa.Column('user_verification_photo_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=True),
    sa.Column('step', sa.Integer(), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('user_verification_photo_id')
    )
    op.add_column(u'user_verifications', sa.Column('address_line_1', sa.String(length=250), nullable=True))
    op.add_column(u'user_verifications', sa.Column('address_line_2', sa.String(length=250), nullable=True))
    op.add_column(u'user_verifications', sa.Column('birthdate', sa.Date(), nullable=True))
    op.add_column(u'user_verifications', sa.Column('city', sa.String(length=128), nullable=True))
    op.add_column(u'user_verifications', sa.Column('country_code', sa.String(length=20), nullable=True))
    op.add_column(u'user_verifications', sa.Column('country_state', sa.String(length=128), nullable=True))
    op.add_column(u'user_verifications', sa.Column('document_date_issued', sa.Date(), nullable=True))
    op.add_column(u'user_verifications', sa.Column('document_type', sa.String(length=256), nullable=True))
    op.add_column(u'user_verifications', sa.Column('first_name', sa.String(length=20), nullable=True))
    op.add_column(u'user_verifications', sa.Column('id_expire_date', sa.Date(), nullable=True))
    op.add_column(u'user_verifications', sa.Column('id_issuing_country', sa.String(length=20), nullable=True))
    op.add_column(u'user_verifications', sa.Column('id_number', sa.String(length=40), nullable=True))
    op.add_column(u'user_verifications', sa.Column('id_type', sa.String(length=20), nullable=True))
    op.add_column(u'user_verifications', sa.Column('institution_name', sa.String(length=256), nullable=True))
    op.add_column(u'user_verifications', sa.Column('last_name', sa.String(length=20), nullable=True))
    op.add_column(u'user_verifications', sa.Column('postal_code', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'user_verifications', 'postal_code')
    op.drop_column(u'user_verifications', 'last_name')
    op.drop_column(u'user_verifications', 'institution_name')
    op.drop_column(u'user_verifications', 'id_type')
    op.drop_column(u'user_verifications', 'id_number')
    op.drop_column(u'user_verifications', 'id_issuing_country')
    op.drop_column(u'user_verifications', 'id_expire_date')
    op.drop_column(u'user_verifications', 'first_name')
    op.drop_column(u'user_verifications', 'document_type')
    op.drop_column(u'user_verifications', 'document_date_issued')
    op.drop_column(u'user_verifications', 'country_state')
    op.drop_column(u'user_verifications', 'country_code')
    op.drop_column(u'user_verifications', 'city')
    op.drop_column(u'user_verifications', 'birthdate')
    op.drop_column(u'user_verifications', 'address_line_2')
    op.drop_column(u'user_verifications', 'address_line_1')
    op.drop_table('user_verification_photos')
    # ### end Alembic commands ###
