"""empty message

Revision ID: 635d8ad9ef0e
Revises: 1fea569bcbb4
Create Date: 2017-09-18 13:04:08.205712

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '635d8ad9ef0e'
down_revision = '1fea569bcbb4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_logged_ip', sa.String(length=15), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_logged_ip')
    # ### end Alembic commands ###
