"""empty message

Revision ID: 6477efbb4edf
Revises: e7e524c34b63
Create Date: 2017-06-01 12:51:30.212026

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6477efbb4edf'
down_revision = 'e7e524c34b63'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('is_requirements_provided', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'is_requirements_provided')
    # ### end Alembic commands ###
