"""empty message

Revision ID: 70d8c93024c0
Revises: 3ff0396e0c85
Create Date: 2017-11-16 14:29:25.921005

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70d8c93024c0'
down_revision = '3ff0396e0c85'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('is_pending', sa.Boolean(), nullable=True))
    op.add_column('orders', sa.Column('stripe_source', sa.String(length=50), nullable=True))
    op.create_index(op.f('ix_orders_stripe_source'), 'orders', ['stripe_source'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_orders_stripe_source'), table_name='orders')
    op.drop_column('orders', 'stripe_source')
    op.drop_column('orders', 'is_pending')
    # ### end Alembic commands ###
