"""empty message

Revision ID: 71ff5ee55f21
Revises: df83e05fdda1
Create Date: 2017-10-26 15:16:05.658531

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71ff5ee55f21'
down_revision = 'df83e05fdda1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('features_json', sa.Text(), nullable=True))
    op.add_column('products', sa.Column('is_highlighted', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'is_highlighted')
    op.drop_column('products', 'features_json')
    # ### end Alembic commands ###
