"""empty message

Revision ID: 78367f899821
Revises: b512000b21bb
Create Date: 2017-03-30 21:10:08.546723

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78367f899821'
down_revision = 'b512000b21bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('primary_photo_key', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'primary_photo_key')
    # ### end Alembic commands ###
