"""empty message

Revision ID: 7884e1103bf9
Revises: 4cd38c69eae4
Create Date: 2017-08-16 13:14:33.996529

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7884e1103bf9'
down_revision = '4cd38c69eae4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('delivery_notification_sent_buyer', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'delivery_notification_sent_buyer')
    # ### end Alembic commands ###
