"""empty message

Revision ID: 7def23d4b595
Revises: 512210274e52
Create Date: 2017-06-15 11:41:01.644509

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7def23d4b595'
down_revision = '512210274e52'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_offers', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product_offers', 'is_deleted')
    # ### end Alembic commands ###
