"""empty message

Revision ID: 7ff31250faa2
Revises: 2a6a2d3bcda6
Create Date: 2017-06-22 15:22:22.827085

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ff31250faa2'
down_revision = '2a6a2d3bcda6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('is_pending_verification', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'is_pending_verification')
    # ### end Alembic commands ###
