"""empty message

Revision ID: 88bb5bd9561e
Revises: c2e1e93b2afa
Create Date: 2017-08-30 12:20:48.755810

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88bb5bd9561e'
down_revision = 'c2e1e93b2afa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('fake_response_time', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'fake_response_time')
    # ### end Alembic commands ###
