"""empty message

Revision ID: 9af2423529c7
Revises: 42a046e621b1
Create Date: 2017-12-11 16:13:23.517307

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9af2423529c7'
down_revision = '42a046e621b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('disputes', sa.Column('resolution_kind', sa.String(length=30), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('disputes', 'resolution_kind')
    # ### end Alembic commands ###
