"""empty message

Revision ID: a956667663e0
Revises: 562917356afc
Create Date: 2017-12-07 11:44:20.428773

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a956667663e0'
down_revision = '562917356afc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('enquiry_offers', sa.Column('enquiry_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'enquiry_offers', 'enquiries', ['enquiry_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'enquiry_offers', type_='foreignkey')
    op.drop_column('enquiry_offers', 'enquiry_id')
    # ### end Alembic commands ###
