"""empty message

Revision ID: ac1e1687e04c
Revises: 010943f52ad0
Create Date: 2018-01-29 15:01:38.252181

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = 'ac1e1687e04c'
down_revision = '010943f52ad0'
branch_labels = None
depends_on = None

REASONS = [
	('non_original_content', 'Non Original Content'),
	('inappropriate_gig', 'Inappropriate Gig'),
	('trademark_violation', 'Trademark Violation'),
	('copytights_violation', 'Copytight Violation')
]


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reports',
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('is_closed', sa.Boolean(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('reason', sqlalchemy_utils.types.choice.ChoiceType(REASONS), nullable=True),
    sa.Column('data_json', sqlalchemy_utils.types.json.JSONType(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('report_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reports')
    # ### end Alembic commands ###
