"""empty message

Revision ID: ae958fae3c6e
Revises: 364561682a06
Create Date: 2017-07-27 10:26:48.596108

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae958fae3c6e'
down_revision = '364561682a06'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('cover_data', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'cover_data')
    # ### end Alembic commands ###
