"""user_verification_hidden

Revision ID: bdd06d81b85a
Revises: ca99be2cb6e2
Create Date: 2018-01-31 09:16:34.231969

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bdd06d81b85a'
down_revision = 'ca99be2cb6e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_verification_photos', sa.Column('hidden', sa.Boolean(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_verification_photos', 'hidden')
    # ### end Alembic commands ###
