"""empty message

Revision ID: c2e1e93b2afa
Revises: 27be1edf6226
Create Date: 2017-08-22 12:20:12.786245

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2e1e93b2afa'
down_revision = '27be1edf6226'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('release_on', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'release_on')
    # ### end Alembic commands ###
