"""empty message

Revision ID: cba8b081230e
Revises: 78367f899821
Create Date: 2017-03-31 13:32:06.371392

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cba8b081230e'
down_revision = '78367f899821'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('published_on', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'published_on')
    # ### end Alembic commands ###
