"""empty message

Revision ID: d25f87674807
Revises: 88bb5bd9561e
Create Date: 2017-08-31 15:12:01.473698

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd25f87674807'
down_revision = '88bb5bd9561e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('meta_data', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'meta_data')
    # ### end Alembic commands ###
