"""empty message

Revision ID: d6b679a35d07
Revises: e39bcc0a49e3
Create Date: 2017-10-23 15:08:39.816547

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6b679a35d07'
down_revision = 'e39bcc0a49e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('delivered_on', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'delivered_on')
    # ### end Alembic commands ###
