"""empty message

Revision ID: ddc879747012
Revises: 5bb0b5578821
Create Date: 2017-01-26 22:21:10.608630

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ddc879747012'
down_revision = '5bb0b5578821'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_bitcoin_addresses_is_current', table_name='bitcoin_addresses')
    op.drop_index('ix_bitcoin_addresses_touched_on', table_name='bitcoin_addresses')
    op.drop_index('ix_contents_created_on', table_name='contents')
    op.drop_index('ix_contents_is_published', table_name='contents')
    op.drop_index('ix_contents_updated_on', table_name='contents')
    op.drop_index('ix_conversations_created_on', table_name='conversations')
    op.drop_index('ix_conversations_updated_on', table_name='conversations')
    op.drop_index('ix_disputes_created_on', table_name='disputes')
    op.drop_index('ix_disputes_is_closed', table_name='disputes')
    op.drop_index('ix_disputes_is_deleted', table_name='disputes')
    op.drop_index('ix_feedbacks_created_on', table_name='feedbacks')
    op.drop_index('ix_messages_read_on', table_name='messages')
    op.drop_index('ix_messages_sent_on', table_name='messages')
    op.drop_index('ix_newsletters_created_on', table_name='newsletters')
    op.drop_index('ix_newsletters_is_sent', table_name='newsletters')
    op.drop_index('ix_newsletters_sent_on', table_name='newsletters')
    op.drop_index('ix_notifications_created_on', table_name='notifications')
    op.drop_index('ix_orders_price', table_name='orders')
    op.alter_column('products', 'is_approved',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
    op.drop_index('ix_products_created_on', table_name='products')
    op.drop_index('ix_products_is_deleted', table_name='products')
    op.drop_index('ix_products_is_disabled', table_name='products')
    op.drop_index('ix_products_is_private', table_name='products')
    op.drop_index('ix_products_price', table_name='products')
    op.drop_index('ix_products_price_offer', table_name='products')
    op.drop_index('ix_products_title', table_name='products')
    op.drop_index('ix_products_updated_on', table_name='products')
    op.drop_index('ix_products_views', table_name='products')
    op.drop_column('products', 'is_verified')
    op.drop_column('products', 'is_disabled')
    op.drop_index('ix_tickets_created_on', table_name='tickets')
    op.drop_index('ix_tickets_is_closed', table_name='tickets')
    op.drop_index('ix_tickets_is_deleted', table_name='tickets')
    op.drop_index('ix_transactions_amount', table_name='transactions')
    op.drop_index('ix_transactions_is_hold', table_name='transactions')
    op.add_column('users', sa.Column('is_disabled', sa.Boolean(), nullable=True))
    op.drop_index('ix_users_last_logged_on', table_name='users')
    op.drop_column('users', 'public_key_fingerprint')
    op.drop_column('users', 'public_key')
    op.drop_column('users', 'is_seller_disabled')
    op.drop_column('users', 'is_two_factor_enabled')
    op.drop_column('users', 'pincode')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('pincode', mysql.VARCHAR(length=8), nullable=False))
    op.add_column('users', sa.Column('is_two_factor_enabled', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('is_seller_disabled', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('public_key', mysql.TEXT(), nullable=True))
    op.add_column('users', sa.Column('public_key_fingerprint', mysql.VARCHAR(length=100), nullable=True))
    op.create_index('ix_users_last_logged_on', 'users', ['last_logged_on'], unique=False)
    op.drop_column('users', 'is_disabled')
    op.create_index('ix_transactions_is_hold', 'transactions', ['is_hold'], unique=False)
    op.create_index('ix_transactions_amount', 'transactions', ['amount'], unique=False)
    op.create_index('ix_tickets_is_deleted', 'tickets', ['is_deleted'], unique=False)
    op.create_index('ix_tickets_is_closed', 'tickets', ['is_closed'], unique=False)
    op.create_index('ix_tickets_created_on', 'tickets', ['created_on'], unique=False)
    op.add_column('products', sa.Column('is_disabled', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
    op.add_column('products', sa.Column('is_verified', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
    op.create_index('ix_products_views', 'products', ['views'], unique=False)
    op.create_index('ix_products_updated_on', 'products', ['updated_on'], unique=False)
    op.create_index('ix_products_title', 'products', ['title'], unique=False)
    op.create_index('ix_products_price_offer', 'products', ['price_offer'], unique=False)
    op.create_index('ix_products_price', 'products', ['price'], unique=False)
    op.create_index('ix_products_is_private', 'products', ['is_private'], unique=False)
    op.create_index('ix_products_is_disabled', 'products', ['is_disabled'], unique=False)
    op.create_index('ix_products_is_deleted', 'products', ['is_deleted'], unique=False)
    op.create_index('ix_products_created_on', 'products', ['created_on'], unique=False)
    op.alter_column('products', 'is_approved',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
    op.create_index('ix_orders_price', 'orders', ['price'], unique=False)
    op.create_index('ix_notifications_created_on', 'notifications', ['created_on'], unique=False)
    op.create_index('ix_newsletters_sent_on', 'newsletters', ['sent_on'], unique=False)
    op.create_index('ix_newsletters_is_sent', 'newsletters', ['is_sent'], unique=False)
    op.create_index('ix_newsletters_created_on', 'newsletters', ['created_on'], unique=False)
    op.create_index('ix_messages_sent_on', 'messages', ['sent_on'], unique=False)
    op.create_index('ix_messages_read_on', 'messages', ['read_on'], unique=False)
    op.create_index('ix_feedbacks_created_on', 'feedbacks', ['created_on'], unique=False)
    op.create_index('ix_disputes_is_deleted', 'disputes', ['is_deleted'], unique=False)
    op.create_index('ix_disputes_is_closed', 'disputes', ['is_closed'], unique=False)
    op.create_index('ix_disputes_created_on', 'disputes', ['created_on'], unique=False)
    op.create_index('ix_conversations_updated_on', 'conversations', ['updated_on'], unique=False)
    op.create_index('ix_conversations_created_on', 'conversations', ['created_on'], unique=False)
    op.create_index('ix_contents_updated_on', 'contents', ['updated_on'], unique=False)
    op.create_index('ix_contents_is_published', 'contents', ['is_published'], unique=False)
    op.create_index('ix_contents_created_on', 'contents', ['created_on'], unique=False)
    op.create_index('ix_bitcoin_addresses_touched_on', 'bitcoin_addresses', ['touched_on'], unique=False)
    op.create_index('ix_bitcoin_addresses_is_current', 'bitcoin_addresses', ['is_current'], unique=False)
    # ### end Alembic commands ###
