"""empty message

Revision ID: df6d7cd53bbc
Revises: ffdfd2c285e2
Create Date: 2017-12-08 14:00:15.153434

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df6d7cd53bbc'
down_revision = 'ffdfd2c285e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_affiliate_panel_enabled', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_affiliate_panel_enabled')
    # ### end Alembic commands ###
