"""empty message

Revision ID: df83e05fdda1
Revises: 32a5c49f5b6c
Create Date: 2017-10-25 15:09:47.518385

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df83e05fdda1'
down_revision = '32a5c49f5b6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deliverables', sa.Column('rating', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('deliverables', 'rating')
    # ### end Alembic commands ###
