"""empty message

Revision ID: e0035538b74f
Revises: 95c94abb9fc1
Create Date: 2017-12-20 21:07:55.594568

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0035538b74f'
down_revision = '95c94abb9fc1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('affiliate_links', sa.Column('is_hidden', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('affiliate_links', 'is_hidden')
    # ### end Alembic commands ###
