"""empty message

Revision ID: e19cad50aa6e
Revises: d25f87674807
Create Date: 2017-09-05 16:08:27.708956

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e19cad50aa6e'
down_revision = 'd25f87674807'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_rsa', sa.String(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password_rsa')
    # ### end Alembic commands ###
