"""empty message

Revision ID: e3d663602a40
Revises: 7f4cf91056f8
Create Date: 2017-12-26 11:57:15.511723

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3d663602a40'
down_revision = '7f4cf91056f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('profile_rate', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'profile_rate')
    # ### end Alembic commands ###
