"""empty message

Revision ID: e5902eccb1e0
Revises: 4faeb5255c1d
Create Date: 2016-12-21 18:20:57.181566

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5902eccb1e0'
down_revision = '4faeb5255c1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'products', sa.Column('data_json', sa.Text(), nullable=False))
    op.add_column(u'products', sa.Column('additional_info_message', sa.Text(), nullable=True))
    op.add_column(u'orders', sa.Column('data_json', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'orders', 'data_json')
    op.drop_column(u'products', 'additional_info_message')
    op.drop_column(u'products', 'data_json')
    # ### end Alembic commands ###
