"""empty message

Revision ID: e6f97e1640e1
Revises: 3d0206f4866e
Create Date: 2017-07-04 11:43:47.428586

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e6f97e1640e1'
down_revision = '3d0206f4866e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notifications')
    op.drop_table('messages')
    op.drop_table('conversations')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversations',
    sa.Column('conversation_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('sender_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('recipient_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('is_hidden_by_sender', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('is_hidden_by_recipient', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('type', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('product_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('dispute_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('ticket_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('order_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('withdrawal_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('newsletter_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('created_on', mysql.DATETIME(), nullable=True),
    sa.Column('updated_on', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['dispute_id'], [u'disputes.dispute_id'], name=u'conversations_ibfk_4'),
    sa.ForeignKeyConstraint(['newsletter_id'], [u'newsletters.newsletter_id'], name=u'conversations_ibfk_8'),
    sa.ForeignKeyConstraint(['order_id'], [u'orders.order_id'], name=u'conversations_ibfk_6'),
    sa.ForeignKeyConstraint(['product_id'], [u'products.id'], name=u'conversations_ibfk_3'),
    sa.ForeignKeyConstraint(['recipient_id'], [u'users.user_id'], name=u'conversations_ibfk_2'),
    sa.ForeignKeyConstraint(['sender_id'], [u'users.user_id'], name=u'conversations_ibfk_1'),
    sa.ForeignKeyConstraint(['ticket_id'], [u'tickets.ticket_id'], name=u'conversations_ibfk_5'),
    sa.ForeignKeyConstraint(['withdrawal_id'], [u'withdrawals.withdrawal_id'], name=u'conversations_ibfk_7'),
    sa.PrimaryKeyConstraint('conversation_id'),
    mysql_default_charset=u'latin1',
    mysql_engine=u'InnoDB'
    )
    op.create_table('messages',
    sa.Column('message_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('conversation_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('sender_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('recipient_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('sent_on', mysql.DATETIME(), nullable=True),
    sa.Column('read_on', mysql.DATETIME(), nullable=True),
    sa.Column('text', mysql.TEXT(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], [u'conversations.conversation_id'], name=u'messages_ibfk_1', ondelete=u'CASCADE'),
    sa.ForeignKeyConstraint(['recipient_id'], [u'users.user_id'], name=u'messages_ibfk_3'),
    sa.ForeignKeyConstraint(['sender_id'], [u'users.user_id'], name=u'messages_ibfk_2'),
    sa.PrimaryKeyConstraint('message_id'),
    mysql_default_charset=u'latin1',
    mysql_engine=u'InnoDB'
    )
    op.create_table('notifications',
    sa.Column('notification_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('type', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('data_json', mysql.TEXT(), nullable=False),
    sa.Column('created_on', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], [u'users.user_id'], name=u'notifications_ibfk_1'),
    sa.PrimaryKeyConstraint('notification_id'),
    mysql_default_charset=u'latin1',
    mysql_engine=u'InnoDB'
    )
    # ### end Alembic commands ###
