"""empty message

Revision ID: e7e524c34b63
Revises: cba8b081230e
Create Date: 2017-04-06 08:37:38.233943

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7e524c34b63'
down_revision = 'cba8b081230e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('delivery_on', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'delivery_on')
    # ### end Alembic commands ###
