"""empty message

Revision ID: ec26b05e5446
Revises: fa3a6d279449
Create Date: 2017-01-11 21:22:27.321879

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec26b05e5446'
down_revision = 'fa3a6d279449'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('social_id', sa.String(length=64), nullable=True))
    op.create_unique_constraint(None, 'users', ['social_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'social_id')
    # ### end Alembic commands ###
