"""empty message

Revision ID: f03e89f120f5
Revises: 7ff31250faa2
Create Date: 2017-06-29 13:52:48.174720

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f03e89f120f5'
down_revision = '7ff31250faa2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone_number', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('phone_number_verified', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phone_number_verified')
    op.drop_column('users', 'phone_number')
    # ### end Alembic commands ###
