"""empty message

Revision ID: f14255148eda
Revises: 9af2423529c7
Create Date: 2017-12-15 13:28:55.242528

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f14255148eda'
down_revision = '9af2423529c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_invitations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=20), nullable=True),
    sa.Column('is_manual', sa.Boolean(), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], onupdate='cascade', ondelete='cascade'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_invitations_email'), 'user_invitations', ['email'], unique=False)
    op.add_column(u'users', sa.Column('invite_referer_id', sa.Integer(), nullable=True))
    op.drop_index('social_id', table_name='users')
    op.create_foreign_key(None, 'users', 'users', ['invite_referer_id'], ['user_id'])
    op.drop_column(u'users', 'social_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'users', sa.Column('social_id', mysql.VARCHAR(length=64), nullable=True))
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_index('social_id', 'users', ['social_id'], unique=True)
    op.drop_column(u'users', 'invite_referer_id')
    op.drop_index(op.f('ix_user_invitations_email'), table_name='user_invitations')
    op.drop_table('user_invitations')
    # ### end Alembic commands ###
