"""empty message

Revision ID: f2c3cf58e20b
Revises: 635d8ad9ef0e
Create Date: 2017-10-17 00:06:00.504775

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f2c3cf58e20b'
down_revision = '635d8ad9ef0e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('SearchSuggest',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('keywords', sa.String(length=90), nullable=False),
    sa.Column('is_approved', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_SearchSuggest_keywords'), 'SearchSuggest', ['keywords'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_SearchSuggest_keywords'), table_name='SearchSuggest')
    op.drop_table('SearchSuggest')
    # ### end Alembic commands ###
