"""empty message

Revision ID: f8f1734767ea
Revises: e5902eccb1e0
Create Date: 2016-12-22 17:28:48.682914

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f8f1734767ea'
down_revision = 'e5902eccb1e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_offers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(u'products', sa.Column('active_offer_id', sa.Integer(), nullable=True))
    op.add_column(u'products', sa.Column('price_offer', sa.Integer(), nullable=True))
    op.alter_column(u'products', 'data_json',
               existing_type=mysql.TEXT(),
               nullable=False)
    op.create_index(op.f('ix_products_price_offer'), 'products', ['price_offer'], unique=False)
    op.create_foreign_key(None, 'products', 'product_offers', ['active_offer_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_index(op.f('ix_products_price_offer'), table_name='products')
    op.alter_column(u'products', 'data_json',
               existing_type=mysql.TEXT(),
               nullable=True)
    op.drop_column(u'products', 'price_offer')
    op.drop_column(u'products', 'active_offer_id')
    op.drop_table('product_offers')
    # ### end Alembic commands ###
