"""empty message

Revision ID: fe3f6db1e170
Revises: 25d44ae321ee
Create Date: 2017-12-18 12:24:19.378655

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql


# revision identifiers, used by Alembic.
revision = 'fe3f6db1e170'
down_revision = '25d44ae321ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bonus_transactions',
    sa.Column('bonus_transaction_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('subtype', sa.String(length=20), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.Column('data_json', sa.Text(), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('bonus_transaction_id')
    )
    op.add_column(u'user_invitations', sa.Column('sent_on', sa.DateTime(), nullable=True))
    op.add_column(u'users', sa.Column('bonus_credit', sa.Integer(), nullable=True))
    op.execute('UPDATE users SET bonus_credit=0')
    op.alter_column(u'users', 'bonus_credit', existing_type=mysql.INTEGER(display_width=11), nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'users', 'bonus_credit')
    op.drop_column(u'user_invitations', 'sent_on')
    op.drop_table('bonus_transactions')
    # ### end Alembic commands ###
