"""empty message

Revision ID: fffd6e29487f
Revises: 70d8c93024c0
Create Date: 2017-11-17 15:15:27.950952

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fffd6e29487f'
down_revision = '70d8c93024c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('discounts', sa.Column('is_hold', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('discounts', 'is_hold')
    # ### end Alembic commands ###
